# Generated by Django 5.2 on 2025-04-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hoteler", "0002_guest_remove_hotel_price_per_night_hotel_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="confirmation_number",
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
